name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Test
      run: |
        chmod +x ./build.sh
        ./build.sh Test --configuration Release

  pack:
    name: Build Package
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Build and Pack
      run: |
        chmod +x ./build.sh
        ./build.sh Pack --configuration Release
    - name: Push Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: libonebot-${{ github.sha }}
        path: dist/
